"""update artist model

Revision ID: cb0791a9b381
Revises: 099a8853ea5f
Create Date: 2022-06-03 22:16:16.828800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0791a9b381'
down_revision = '099a8853ea5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('venue_search', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('Artist', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'created_at')
    op.drop_column('Artist', 'description')
    op.drop_column('Artist', 'venue_search')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
